### ISSUE TITLE
`hello_world` example crashes

### ISSUE THREAD

**Issue by maxfrei750** [IntelligentPMT/synthPIC2#1]
```
 user@9fd31e908465:/workspace$ python run.py --config-dir=recipes --config-name=hello_world
Traceback (most recent call last):
  File "/workspace/run.py", line 3, in <module>
    from synthpic2 import execute_recipe
  File "/workspace/synthpic2/__init__.py", line 3, in <module>
    from .engine import execute_recipe
  File "/workspace/synthpic2/engine.py", line 23, in <module>
    import bpy
ImportError: /opt/bpy/lib/python3.10/site-packages/bpy.so: undefined symbol: SharpYuvInit
user@9fd31e908465:/workspace$
```

**Comment by maxfrei750** [comment]
Fixed.
